# Generated by Django 2.2.6 on 2019-10-22 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191022_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 9, 23, 6, 515584)),
        ),
    ]
