# Generated by Django 2.2.6 on 2019-10-22 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20191022_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 13, 52, 13, 691407)),
        ),
    ]
