# Generated by Django 2.2.6 on 2019-10-22 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20191022_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 14, 36, 43, 217698)),
        ),
    ]
