# Generated by Django 2.2.6 on 2019-10-27 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20191022_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 6, 57, 41, 388626)),
        ),
    ]
