# Generated by Django 2.2.6 on 2019-10-28 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20191027_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.Category'),
        ),
        migrations.AlterField(
            model_name='events',
            name='check',
            field=models.CharField(default='off', max_length=3),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 12, 45, 9, 705836)),
        ),
    ]
